version: "3.8"

services:
  backend:
    build:
      context: ../repository/backend
      dockerfile: B-Spcfy/Dockerfile
    container_name: spcfy-backend
    volumes:
      - ../repository/backend/B-Spcfy/data:/app/data
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      - CONSOLE_URL=http://localhost:3001
      - DASHBOARD_URL=http://localhost:3000
      - DOTNET_ENVIRONMENT=Development
      - EMAIL_SERVICE=None
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    env_file:
      - ../repository/backend/.env
    networks:
      - spcfy
  database:
    build:
      context: ../repository/service-postgres
    container_name: spcfy-database
    ports:
      - "8082:5432"
    env_file:
      - ../repository/service-postgres/.env
    networks:
      - spcfy
    volumes:
      - postgres-data:/var/lib/postgresql/data
  frontend-dashboard:
    build:
      context: ../repository/frontend-dashboard
      target: src
    container_name: spcfy-frontend-dashboard
    volumes:
      - ../repository/frontend-dashboard/src:/usr/src/app/src
      - ../repository/frontend-dashboard/public:/usr/src/app/public
      - ../repository/frontend-dashboard/.storybook:/usr/src/app/.storybook
    ports:
      - "3000:3000"
    env_file:
      - ../repository/frontend-dashboard/.env
    networks:
      - spcfy
    command: "yarn run start"
  storybook:
    build:
      context: ../repository/frontend-dashboard
      target: src
    container_name: spcfy-storybook
    volumes:
      - ../repository/frontend-dashboard/src:/usr/src/app/src
      - ../repository/frontend-dashboard/public:/usr/src/app/public
      - ../repository/frontend-dashboard/.storybook:/usr/src/app/.storybook
    ports:
      - "6006:6006"
    env_file:
      - ../repository/frontend-dashboard/.env
    networks:
      - spcfy
    command: "yarn run storybook"
  frontend-console:
    build:
      context: ../repository/frontend-console
      target: src
    container_name: spcfy-frontend-console
    volumes:
      - ../repository/frontend-console/src:/usr/src/app/src
      - ../repository/frontend-console/public:/usr/src/app/public
      - ../repository/frontend-console/.storybook:/usr/src/app/.storybook
    ports:
      - "3001:3001"
    env_file:
      - ../repository/frontend-console/.env
    networks:
      - spcfy
    command: "yarn run start"

networks:
  spcfy:
    driver: bridge

volumes:
  postgres-data: